# 313448888
# israele4

compile: bin
	javac -cp src:biuoop-1.4.jar -d bin src/*.java
	
run2:
	java -cp .:bin:biuoop-1.4.jar AbstractArtDrawing
	
run3.2:
	java -cp .:bin:biuoop-1.4.jar BouncingBallAnimation
	
run3.3:
	java -cp .:bin:biuoop-1.4.jar:. MultipleBouncingBallsAnimation 12 2 3 4 2 9

run3.4:
	java -cp .:bin:biuoop-1.4.jar:. MultipleFramesBouncingBallsAnimation 12 2 3 4 2 9

bin:
	mkdir bin